
version: 2
jobs:
  job1:
    docker:
      - image: alpine:latest
    steps:
      - run: echo AA
  job2:
    docker:
      - image: alpine:latest
    steps:
      - run: echo AA
  job3:
    docker:
      - image: alpine:latest
    steps:
      - run: echo AA
  job4:
    docker:
      - image: alpine:latest
    steps:
      - run: echo AA

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - job1
      - job2
      - job3:
          requires:
            - job1
            - job2
      - job4:
          requires:
            - job3
