name: Super-Linter

on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo AAA
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo AAA
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo AAA
  asdasdasd:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo AAA
  BBBBBBBBBB:
    needs: 
      - test
      - asdasdasd
    runs-on: ubuntu-latest
    steps:
      - run: echo AAA
